version: "3"

services:
    web:
      build: .
      container_name: "python_app"
      ports:
         - "8000:8000"
      depends_on:
         - redis
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
      volumes:
         - redis:/var/lib/redis  
    redis:
      image: "redis:alpine"
      container_name: "redis"

volumes:
    redis:
      driver: local
    
